# Generated by Django 3.0.6 on 2020-05-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('cake', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake.Cake')),
            ],
        ),
    ]
