# Generated by Django 3.0.6 on 2020-05-07 17:58

from django.db import migrations


def create_positions(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Position = apps.get_model('cake', 'Position')
    obj = Position()
    for position in range(1, 1750):
        obj.pk = None
        obj.position = position
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cake', '0002_position'),
    ]

    operations = [
        migrations.RunPython(create_positions),
    ]
