# Generated by Django 3.0.6 on 2020-05-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_auto_20200507_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
